export const contributors = [
    {
        name: 'Tanvi Sharma',
        email: 'tanvi.s@example.com',
        profilelink: 'https://peerconnect.dev/users/tanvisharma',
        avatar: '',
        contributorSince: '2025-03-01',
    },
    {
        name: 'Aryan Mehta',
        email: 'aryan.m@example.com',
        profilelink: 'https://peerconnect.dev/users/aryanmehta',
        avatar: '',
        contributorSince: '2025-02-15',
    },
    {
        name: 'Ishita Verma',
        email: 'ishita.v@example.com',
        profilelink: 'https://peerconnect.dev/users/ishitaverma',
        avatar: '',
        contributorSince: '2025-04-02',
    },
    {
        name: 'Rohan Das',
        email: 'rohan.d@example.com',
        profilelink: 'https://peerconnect.dev/users/rohandas',
        avatar: '',
        contributorSince: '2025-01-20',
    },
    {
        name: 'Neha Kapoor',
        email: 'neha.k@example.com',
        profilelink: 'https://peerconnect.dev/users/nehakapoor',
        avatar: '',
        contributorSince: '2025-03-10',
    },
    {
        name: 'Kunal Roy',
        email: 'kunal.r@example.com',
        profilelink: 'https://peerconnect.dev/users/kunalroy',
        avatar: '',
        contributorSince: '2025-02-05',
    },
    {
        name: 'Simran Kaur',
        email: 'simran.k@example.com',
        profilelink: 'https://peerconnect.dev/users/simrankaur',
        avatar: '',
        contributorSince: '2025-03-22',
    },
    {
        name: 'Aditya Nair',
        email: 'aditya.n@example.com',
        profilelink: 'https://peerconnect.dev/users/adityanair',
        avatar: '',
        contributorSince: '2025-01-30',
    },
];
